firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess adminClientEmail
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess adminPrivateKey
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess authCookieName
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess authCookieSignatureCurrent
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess authCookieSignaturePrevious
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseApiKey
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseAuthDomain
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseAuthToken
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseCertX509
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseClientId
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseDbUrl
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseProjectId
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseSenderId
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess useSecureCookies
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess canvaAppPlatformId
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess canvaConnectPlatformId
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess canvaConnectPlatformSecret
firebase --project caiman-75133 --backend caiman apphosting:secrets:grantaccess firebaseWebAppId
